CONVERT_TO = helios

CAPS_WORD_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
SPLIT_OLED_ENABLE = yes

RGBLIGHT_ENABLE = yes
#RGBLIGHT_DRIVER = SK6812mini
RGBLIGHT_DRIVER = ws2812
# SK6812MINI
# RGBLIGHT_DRIVER = sk6812
# RGBLIGHT_MODE_STATIC_LIGHT = yes
# RGBLIGHT_ENABLE_MODE_STATIC_LIGHT = yes
# RGBLIGHT_CONFIG_HUE    = 128
# RGBLIGHT_CONFIG_SAT    = 255
# RGBLIGHT_CONFIG_VAL    = 255
# WS2812_DI_PIN=D3
RGB_DI_PIN = D3
#_PIN=D3
# driver, ws2812 : pin D3
# PS2_DRIVER = vendor
# POINTING_DEVICE_DRIVER = ps2
#POINTING_DEVICE_DRIVER = trackpoint
#MSG_POINTING_DEVICE = trackpoint
# PS2_MOUSE_ENABLE = yes
# PS2_ENABLE = yes
# PS2_DRIVER = busywait
# SPLIT_POINTING_ENABLE = yes
# PS2_DRIVER = busywait
