CAPS_WORD_ENABLE = yes
CONVERT_TO=helios

# PS2_DRIVER = vendor
# POINTING_DEVICE_DRIVER = ps2
#POINTING_DEVICE_DRIVER = trackpoint
#MSG_POINTING_DEVICE = trackpoint

# PS2_MOUSE_ENABLE = yes
# PS2_DRIVER = busywait
